In [1]:
import pandas as pd

In [2]:
train_df = pd.read_csv('/Users/priyanshu.tuli/Desktop/machinehack/emotions_prediction/Dataset/train.csv')

In [3]:
train_df.head()

  Image_name  Emotion
0  63119.png    happy
1  61769.png  neutral
2  95472.png  disgust
3  93515.png  neutral
4  56585.png    angry

In [4]:
train_df.shape

(7102, 2)

In [5]:
test_df = pd.read_csv('/Users/priyanshu.tuli/Desktop/machinehack/emotions_prediction/Dataset/test.csv')

In [6]:
test_df.head()

  Image_name
0  84757.png
1  57211.png
2  28038.png
3  16408.png
4  43196.png

In [7]:
test_df.shape

(3045, 1)

In [8]:
train_df['Emotion'].value_counts()

Emotion
happy        1008
neutral       899
disregard     881
fear          871
surprise      871
sorrow        871
angry         851
disgust       850
Name: count, dtype: int64