In [1]:
import pandas as pd
import numpy as np

In [2]:
train_df = pd.read_csv("/Users/priyanshu.tuli/Desktop/machinehack/sequence_classification/Dataset/Train.csv")

In [3]:
train_df.head()

,Unnamed: 0,text,genre,label,label_model,text_cleaned
0,0,"It starts with pain, followed by hate\nFueled ...",rock,9,LABEL_9,"It starts with pain, followed by hate\nFueled ..."
1,1,Freedom!\nAlone again again alone\nPatiently w...,rock,9,LABEL_9,Freedom!\nAlone again again alone\nPatiently w...
2,2,"Biting the hand that feeds you, lying to the v...",rock,9,LABEL_9,"Biting the hand that feeds you, lying to the v..."
3,3,You say you know just who I am\nBut you can't ...,rock,9,LABEL_9,You say you know just who I am\nBut you can't ...
4,4,My heart is beating faster can't control these...,rock,9,LABEL_9,My heart is beating faster can't control these...

In [4]:
train_df.drop(columns=['Unnamed: 0'], inplace=True)

In [5]:
train_df.head()

,text,genre,label,label_model,text_cleaned
0,"It starts with pain, followed by hate\nFueled ...",rock,9,LABEL_9,"It starts with pain, followed by hate\nFueled ..."
1,Freedom!\nAlone again again alone\nPatiently w...,rock,9,LABEL_9,Freedom!\nAlone again again alone\nPatiently w...
2,"Biting the hand that feeds you, lying to the v...",rock,9,LABEL_9,"Biting the hand that feeds you, lying to the v..."
3,You say you know just who I am\nBut you can't ...,rock,9,LABEL_9,You say you know just who I am\nBut you can't ...
4,My heart is beating faster can't control these...,rock,9,LABEL_9,My heart is beating faster can't control these...

In [6]:
train_df.shape

(290183, 5)

In [7]:
from transformers import AutoTokenizer

/Users/priyanshu.tuli/Desktop/machinehack/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [8]:
tokenizer = AutoTokenizer.from_pretrained("distilbert/distilbert-base-uncased")

In [40]:
def preprocess_function(examples):
    return tokenizer(examples['text_cleaned'], truncation=True)

In [11]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290183 entries, 0 to 290182
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   text          290148 non-null  object
 1   genre         290183 non-null  object
 2   label         290183 non-null  int64
 3   label_model   290183 non-null  object
 4   text_cleaned  290147 non-null  object
dtypes: int64(1), object(4)
memory usage: 11.1+ MB

In [12]:
train_df.isna().sum()

text            35
genre            0
label            0
label_model      0
text_cleaned    36
dtype: int64

In [13]:
train_df.loc[train_df['text_cleaned'].isna(), ['label']]

        label
4080        7
4103        9
4114        9
4123        9
10491       9
22948       6
26925       9
27750       7
27921       7
41405       6
42081       6
50429       9
50943       9
51284       9
52245       6
52532       9
54956       9
54988       9
60061       7
68494       9
94654       7
105117      7
105127      7
105138      7
105162      7
105199      7
105206      7
105210      7
105216      7
107144      7
109412      7
124519      7
124536      7
125896      7
135123      7
164132      7

In [14]:
train_df.dropna(inplace=True)

In [16]:
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer

In [17]:
from transformers import DataCollatorWithPadding

In [18]:
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [19]:
import evaluate

In [20]:
accuracy = evaluate.load("accuracy")

In [21]:
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return accuracy.compute(predictions=predictions, references=labels)

In [22]:
labels = train_df[['label', 'genre']].to_dict(orient='records')

In [23]:
labels = set([(label['label'], label['genre']) for label in labels])

In [24]:
labels

{(0, 'country'),
 (1, 'electronic'),
 (2, 'folk'),
 (3, 'hip-hop'),
 (4, 'indie'),
 (5, 'jazz'),
 (6, 'metal'),
 (7, 'pop'),
 (8, 'r&b'),
 (9, 'rock')}

In [25]:
id2label = {label[0]: label[1] for i, label in enumerate(labels)}
label2id = {label: i for i, label in id2label.items()}

In [26]:
id2label, label2id

({9: 'rock',
  8: 'r&b',
  5: 'jazz',
  6: 'metal',
  4: 'indie',
  0: 'country',
  7: 'pop',
  3: 'hip-hop',
  1: 'electronic',
  2: 'folk'},
 {'rock': 9,
  'r&b': 8,
  'jazz': 5,
  'metal': 6,
  'indie': 4,
  'country': 0,
  'pop': 7,
  'hip-hop': 3,
  'electronic': 1,
  'folk': 2})

In [27]:
model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert/distilbert-base-uncased", num_labels=10, id2label=id2label, label2id=label2id
)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert/distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
train_df, eval_df = train_test_split(train_df, test_size=0.2)

In [37]:
req_train_df = train_df[['text_cleaned', 'label']]
req_eval_df = eval_df[['text_cleaned', 'label']]

In [47]:
req_train_dict = req_train_df.to_dict(orient='list')
req_eval_dict = req_eval_df.to_dict(orient='list')

In [48]:
req_eval_dict

{'text_cleaned': ["Pretty amazing grace is what You showed me\nPretty amazing grace is who You are\nI was an empty vessel\nYou filled me up inside\nAnd with amazing grace restored my pride\n\nPretty amazing grace is how You saved me\nAnd with amazing grace reclaimed my heart\nLove in the midst of chaos\nCalm in the heat of war\nShowed with amazing grace what love was for\n\nYou forgave my insensitivity\nAnd my attempt to then mislead You\nYou stood beside a wretch like me\nYour pretty amazing grace was all I needed.\n\nStumbled inside the doorway of Your chapel\nHumbled in God by everything I found\nBeauty and love surround me\nFreed me from what I fear\nAsk for amazing grace and You appear\n\nYou overcame my loss of hope and faith\nGave me a truth I could belive in\nYou led me to a higher place\nShowed Your amazing grace\nWhen grace was what I needed\n\nLook in a mirror I see Your reflection\nOpen a book You live on every page\nI fall and You're there to lift me\nShare every road I climb\nAnd with amazing grace You ease my mind\n\nCame to You with empty pockets first\nWhen I returned I was rich man\nDidn't believe love could quench my thirst\nBut with amazing grace You showed me that it can\n\nIn Your amazing grace I had a vision\nFrom that amazing place I came to be\nInto the night I wandered\nWandering aimlessly\nFound Your amazing grace to comfort me.\n\nPretty amazing\nPretty amazing\nPretty amazing\nPretty amazing\nPretty amazing\nPretty amazing\nPretty amazing\nPretty amazing\n\nYou overcame my loss of hope and faith,\nGave me a truth I could believe in.\nYou led me to that higher place\nShowed me that love and truth and hope and grace were all I needed.",
  "IT'S OVER\n(Tom Evans)\nPack my bag, I'm going away\nIt's over\nGoing home\nThank you people\nbut it's too much to stay\nIt's done now, I'm going home\nNow I feel like I'm warm\nNow I feel like I'm tuned\nSpent my time and some fun\nAnd for that I thank you\nIt's over, it's over\nIt's over\nI'm going home\nIt's over, it's over\nAnd for that I thank you\nNow I feel like I'm warm\nNow I feel like I'm tuned\nSpent my time and some fun\nAnd for that I thank you\nIt's over, it's over\nIt's over\nI'm going home\nIt's over, it's over\nAnd for that I thank you",
  'Meu avô tocou viola\nO meu pai é sertanejo\nFui crescendo com a viola\nSendo aluno dessa escola\nSou feliz agora vejo\nEu colhi felicidade\nPelos circos e coretos\nPelos cantos e cidades\nO meu pai cantou verdade\nE o meu tio fez o dueto\n(Craveiro e Cravinho) Citação: Adeus morena, adeus\nNa casa de Mané Pedro\nFoi numa festa de São João\nCantei moda de viola,\nCateretê lá do meu sertão\nToada paraguaiana\nRemexe no coração\nEu fiz a velha chorar\nE a moça sentir paixão\nEu fiz a velha chorar\nE a moça sentir paixão\n(César e Paulinho)\nCraveiro e cravinho\nSomos fãs e frutos seus\nSomos Cézar e Paulinho\nProsseguindo com carinho\nA missão que Deus nos deu\n(Ed e Fábio Cezar)\nO meu pai vive na estrada\nO meu tio é companheiro\nEnfrentando as jornadas\nNoites, dias, madrugadas\nE a esperança o tempo inteiro\nUma dupla sertaneja\nQue canta desde menino\nUm dueto tão bonito\nEcoando no infinito\nMaravilha, dom divino\n(Cézar e Paulinho) Citação: O Feijão e a Flor\nA flor era você\nE o feijão era eu\nAbraçados um ao outro\nComigo você cresceu\n*Meus filhos, e meus sobrinhos..\nEd e Fábio Cezar\n(Ed e Fábio Cezar)\nÉ um dom de pai pra filho\nCantar mensagens de amor\nConfirmando as referências\nHoje somos a seqüência\nGeração de cantador\n(Cézar e Paulinho)\nÉ um dom de pai pra filho\nCantar mensagens de amor\nConfirmando as referências\nHoje somos a seqüência\nGeração de cantador\n(Craveiro e Cravinho)\nÉ um dom de pai pra filho\nCantar mensagens de amor\nConfirmando as referencias\nHoje somos a seqüência\nGeração de cantador',
  "Au petit trot s'en va le cheval avec ses grelots\nEt le traneau joyeusement dvale travers les cteaux\nDans le vallon s'accroche l'hiver mais le ciel est bleu\nAh qu'il fait bon faire un tour au grand air\nComme deux amoureux\nAt a gentle trot goes the horse with its bells\nAnd the sledge happily goes around the slopes\nIn the small valley sticks the winter but the sky is blue\nAh it's so good to take a ride in the fresh air\nLike two lovers\nA di hop, a di hop, a di hop, oh hey!\nOh hey! du traneau\nEmmitouflez-vous bien dans vos manteaux\nA di hop, a di hop, a di hop, oh hey!\nPour se tenir chaud\nL'un contre l'autre on se blottis comme deux moineaux dans un nid\nC'est merveilleux de voir dfilant comme un dcor peint\nDevant nos yeux les villages tout blancs et les petits sapins\nParfois tu cris car a penche un peu c'est l'instant d'effroi\nMoi je souris j'ai le coeur amoureux et le bout du nez froid\nA di hop, a di hop, a di hop, oh hey!\nOh hey! on the sledge\nMuffle you up well in your coats\nA di hop, a di hop, a di hop, oh hey!\nTo keep us warm\nOne against the other we curl up like two sparows in a nest\nIt's wonderful to see passing by like a painted scenery\nIn front of our eyes the villages all white and the small firs\nSometimes you shout out because it's tilts it's the moment of fear\nI'm smiling i have a heart in love and the tip of the nose cold\nL'attelage a dj pris le chemin du retour\nNous allons tre surpris par la tombe du jour\nCar c'est l'heure o la nuit sans bruit s'panouit comme une fleur\nEt s'allume le ciel qui change de couleurs\nMais voici notre maison qui nous fait signe au loin\nSa lumire l'horizon scintille comme un point\nJe me vois dj prs de toi le rire aux yeux le coeur content\nPrs du grand feu de bois qui flambe et nous attend\nThe harnessing has already taken its way back\nWe will be surprised by the nightfall\nBecause it's the time when the night without a sound causes like a flower\nAnd lights on the sky which changes colors\nBut there's our house that makes us a sign from far away\nIt's light over the horizon sparkles like a dot\nI already see myself by your side laugh in the eyes heart happy\nNear the big wood fire that burns and waiting for us\nAu petit trot s'en va le cheval avec ses grelots\nEt le traneau joyeusement dvale travers les cteaux\nDans le vallon s'accroche l'hiver mais le ciel est bleu\nAh qu'il fait bon faire un tour au grand air\nComme deux amoureux\nAt a gentle trot goes the horse with its bells\nAnd the sledge happily goes around the slopes\nIn the small valley sticks the winter but the sky is blue\nAh it's so good to take a ride in the fresh air\nLike two lovers\nA di hop, a di hop, a di hop, oh hey!\nOh hey! du traneau\nEmmitouflez-vous bien dans vos manteaux\nA di hop, a di hop, a di hop, oh hey!\nPour se tenir chaud\nL'un contre l'autre on se blottis comme deux moineaux dans un nid\nC'est merveilleux de voir dfilant comme un dcor peint\nDevant nos yeux les villages tout blancs et les petits sapins\nParfois tu cris car a penche un peu c'est l'instant d'effroie\nMoi je souris j'ai le coeur amoureux et le bout du nez froid\nA di hop, a di hop, a di hop, oh hey!\nOh hey! on the sledge\nMuffle you up well in your coats\nA di hop, a di hop, a di hop, oh hey!\nTo keep us warm\nOne against the other we curl up like two sparows in a nest\nIt's wonderful to see passing by like a painted scenery\nIn front of our eyes the villages all white and the small firs\nSometimes you shout out because it's tilts it's the moment of fear\nI'm smiling i have a heart in love and the tip of the nose cold\nMoi je souris j'ai le coeur amoureux et le bout du nez froid\nI'm smiling i have a heart in love and the tip of the nose cold",
  "Chorus:\nThis time I'm not gonna stay\nThis time I must get away\nThis time you've gone to far\nThis time I'm not gonna stay\nThis time you've got to pay\nThis time you've gone to far\n\nYou runnin' 'round\nWith those nasty hoes\nHow long did ya think I can take this\nYou said to me\nThat's the way life goes\nHow long did you think I can take this\nI should have known\nAw you weren't for real\nBut my love for you kept on strong\nYou betta know\nYou gonna miss my love\nNow you know that I'm not still holdin' on\nThat's right all of my friends say\n\nRepeat Chorus:\n\nYou've played the game\nBut You played yourself\nOh boy take a look at who's sorry now\nYou're not the same\nAw, how you changed\nSo now look at you\nIt's a damn shame\nI don't care if I\nNever ever see your face again\nYou broke my heart one too many times\nYou think that I'm\nI'm just not that strong\nMy bags are packed\nWatch me walk right through that door",
  "Life is a moment in space\nWhen the dream is gone\nIt's a lonelier place\nI kiss the morning goodbye\nBut down inside you know we never know why\nThe road is narrow and long\nWhen eyes meet eyes\nAnd the feeling is strong\nI turn away from the wall\nI stumble and fall\nBut I give you it all\nI am a woman in love\nAnd I'd do anything\nTo get you into my world\nAnd hold you within\nIt's a right I defend\nOver and over again\nWhat do I do ?\nWith you eternally mine\nIn love there is no measure of time\nThey planned it all at the start\nThat you and I live in each others heart\nWe may be oceans away\nYou feel my love\nI hear what you say\nNo truth is ever a lie\nI stumble and fall\nBut I give you it all\nI am a woman in love\nAnd I'd do anything\nTo get you into my world\nAnd hold you within\nIt's a right I defend\nOver and over again\nWhat do I do ?\nI am a woman in love\nAnd I'm talkin' to you\nI know how you feel\nWhat a woman can do\nIt's a right I defend\nOver and over again\nI am a woman in love\nAnd I'd do anything\nTo get you into my world\nAnd hold you within\nIt's a right I defend\nOver and over again",
  '(Verse) You know, the landlord rang my front door bell, I let it ring for a long, long spell, I went to the window, peaked through the bar, Tell me what was on the old mans mind. (Chorus) Money, honey, Money, honey, Money, honey, If you wanna stay here with me. (Verse) I scream and I scream and Im so hard pressed I call the woman that I love best. I finally reached my baby by half past three I said I like to do what you want with me. She said (Chorus) Money, honey, Money, honey, Money, honey, If you wanna get along with me. (Verse) She screamed and said whats wrong with you? Just stay home, problem is stay trough I said, tell me, baby, face to face, How could another man take my place? She said (Chorus) Money, honey, Money, honey, Money, honey, If you wanna get along with me. (Verse) I learned my lesson and now I knew They saw me shining, with me blue. When my day come and where my day go But though I say how I love em so. I want the (Chorus) Money, honey, Money, honey, Money, honey, If you wanna stay here with me.',
  "It all started out so innocently\nyou were just another pretty face\nthat I loved to see\nbut somewhere down the line\nI got this feeling deep inside\nthat won't stop talking to me\nyeah, it won't stop talking to me\nbut lately I started to dream\nabout you and me\nand how it would be\nto hold you close to me\nlike it's supposed to be\nbut then I get this ringing in my ear\nand it brings me right back to reality\noh, reality, yeah\nwould you bat your eyes and smile\nand kiss me like it was in style\nand tell me you feel the same, yeah\nwould you be surprised and yet uncomfortable\nif I were to send my heart your way\nwhat should I do\nI'm falling in love with you\nbut lately I started to dream\nabout you and me\nand how it would be\nto hold your close to me\nlike it's supposed to be\nbut then I get this ringing in my ear\nand it brings me right back to reality\noh, reality, yeah\nhelp me, I think I'm falling\nin love with you\nhelp me, I think I'm falling, yeah\nin love with you, yeah, yeah, yeah, yeah\nin love with you, yeah, yeah, yeah, yeah\nlove you, yeah",
  'Dear Robin \nHope you dont mind me writing, its just that theres more than one thing I \nneed to ask you. If youre so anti-fashion, why not wear flares, instead of \ndressing down all the same. Its just that looking like that I can express \nmy dissatisfaction. \n\nDear Robin \nLet me explain, though youd never see in a million years. Keep quoting \nCabaret, Berlin, Burroughs, J.G. Ballard, Duchamp, Beauvoir, Kerouac, \nKierkegaard, Michael Rennie. I dont believe you really like Frank Sinatra. \n\nDear Robin \nYoure always so happy, how the hell do you get your inspiration? Youre \nlike a dumb patriot. If youre supposed to be so angry, why dont you fight \nand let me benefit from your right? Dont you know the only way to change \nthings is to shoot men who arrange things, Dear Robin \nI would explain but youd never see in a million years. Well, youve made \nyour rules, but we dont know that game, perhaps Id listen to your records \nbut your logics far too lame and Id only waste three valuable minutes of \nmy life with your insincerity. \n\nYou see Robin, Im just searching for the young soul rebels, and I cant \nfind them anywhere. Where have you hidden them? \n\nMaybe you should welcome the new soul vision. \n',
  "We would always have the ability to start off right (right)\nBy the end of the night we end up in a fight (whoa)\nGirl you said you'd never leave me, but you might\nThis time, this time, this time\nWe was doing so damn good for so damn long\nBut as you can see something went terribly wrong (whoa)\nI been through this so I can stay strong\nThis time, this time, this time\nSeparated, separated, separated, separated\nCause yesterday was cool and the day before\nBut tomorrow will never be no more of\nSeparated\nCause yesterday was cool and the day before\nBut tomorrow will never be no more of\nSeparated\nWe would always have the ability to pull it back together\n(Gether, gether, gether)\nAnd you was always down for me,\nYou ain't give a fungress to whateva (evaaa...)\nBut now you're here telling me that you deserve betta\nThis time, this time (this time)\nHey, and now im sitting here in the dark with nobody\nAnd I don't wanna be alone I need my shawty\nCause luxury means nothing without the luxury of love\nWe're separated, separated, separated, separated\nCause yesterday was cool and the day before\nBut tomorrow there will be no more of\nSeparated\nCause yesterday was cool and the day before\nBut tomorrow there will be no more of (hooo hooo ooooh)\nSeparated",
  "[intro]\nOhh-ohh-ohh\nOhh-ohh-ohh, uh\n[verse]\nHigh speed chase like I'm looking for something\nHigh speed chase like I'm looking for something\nNo more time second guessing, it's pointless\n3-4-5, Miles away from your doorway\nHigh speed chase cause\nI'm running from something\nI woke up feeling less of a lover\nWe won't last but I like to imagine\nSweet like wine on the lips of another\nI've been getting over done on hope\nI will never let that go\nAnd I know just a little something, a little\nHigh speed chase like I'm looking for something\nBreathe so deep, I can taste all the glory\n5 Feet down from my lips to the ground now\n10-9-8 Seconds up out a countdown",
  "Next to the highway - a noisy place.\nWill anyone ever want me?\nTiny place next to the highway.\nCould anyone ever want me?\nI don't have a car;\nMy job pays poor.\nSo much love in my heart.\nLooks as if I may have lost my allure,\nBut I've got much love in my heart.\n\nMy appetite for love's voracious.\nWill anyone entertain me?\nIt's no wonder my bed seems spacious.\nCould anyone entertain me?\nIs it possible\nFor two of us\nTo have much love in our hearts?\nHow it would be\nFortuitous\nTo find that much love in a heart?\n\nThe heat of winter's chill on my face.\nBurning that's deep in my chest.\nIt's cold and familiar in second place,\nKnowing I've done my best.\n\nThe certain cause for my ambition,\nTo dress an unyielding sadness.\nFlirting with an absent addition,\nTo simmer away my madness.\nThe curb that I climb\nIs much too steep\nTo carry that heavy a heart.\nI'll stay where I stand\nAnd just try to keep\nLove in that heavy a heart.\n\nAway from the highway - a quiet place.\nWill I ever find my true love?\nMajestic and far from the highway.\nCould I have had my last love?\nI ride in a plane,\nMy job pays high.\nStill so much love in my heart.\nAt least I'll be sure of my place in the sky,\nWith all this love in my heart.",
  "I see the world, no techni-color But I suppose, I better keep my head up All truth exposed I've been thinking, drinking, If I must admit And to the haters, spectators, talking shit Keep your chicks close Electrik People know na-ah, oh-oh Y' all can't break this Keep your chicks close as sexy as they go, ah-ah, oh-oh Y' all can't break this Keep your chicks close as sexy as they go, oh oh Y' all can't break this Get lost, get loud, get paid, give hope away I thought I made myself a burden tried to fly away But the foolish notion y'all can break this Watch your back, click clack Keep your chicks close Electrik People know na-ah, oh-oh Y' all can't break this Keep your chicks close as sexy as they go, na-ah, oh-oh Y' all can't break this Y' all can't break this Keep your chicks close as sexy as they go, oh oh Y' all can't break this Y' all can't break this Keep your chicks close Electrik People know na-ah, oh-oh Y' all can't break this Keep your chicks close Electrik People know na-ah, oh-oh Keep your chicks close as sexy as they go, oh oh Y' all can't break this Y' all can't break this Y' all can't break this",
  "How long do you think\nYou will stand a fool in the Desert\nA boy with no plan\nThe day's on her last leg again\n\nI cross it all slowing while the next\none comes in\nBut it don't really matter\nNo\n\nYou can't have the world see you like this\nAnd you can't stay for more than a Night\nThat you'll be close where you are\nAnd that I will be missed\n\nBut still I cant turn out the\nLights\nI don't want to live in limbo baby\nI don't want to come home to an empty bed\n\nSaid I'm so tired of the quiet baby\nAnd I'm to young to play\nDead\nSo come on and go out with grace\n\nLay down for a season and down for the rain\nSay you can't have the world see you like this\nAnd you can't stay for more than a Night\nThat you'll be close where you are\n\nAnd that I will be missed\nBut still I cant turn out the\nLights\nI can hear you footsteps at the front door\n\nI can feel your heart pressed upon your poor soul\nBut it don't really matter\n'Cuz you'll be home Come November\nI can see you tremble from here\n\nI can see you tremble from here\nAnd I think I'm gonna to break soon\nSaid I think I'm gonna break soon\nYou can't have the world see you like this\n\nAnd you can't stay for more than a Night\nI can hear you footsteps at the front door\nI can feel your heart pressed upon your poor soul\nBut it don't really matter\n\nNo it don't really matter\nYou can't have the world see you like this\nAnd you can't stay for more than a Night\nThat you'll be close where you are\n\nAnd that I will be missed\nBut still I cant turn out the\nLights\nI can hear you footsteps at the front door\n\nI can feel your heart pressed upon your poor soul\nBut it don't really matter\nYou'll be home come November",
  'O certo era nem pensar em voltar\nNem mais te ver\nNem te ligar\nO certo era a gente nem conversar\nTentar fugir\nNem procurar\nMas quando eu te vejo ainda dói\nSe chega de surpresa me corrói inteiro\nEu entro em desespero\nNão me lembrava de você sem mim\nA gente foi tão feliz\nPor quê?\nSe eu pudesse escolher\nNunca teria amado\nVocê\nMas a chuva não pede pra cair\nO sol tem hora certa pra nascer\nSerá que estava escrito\nQue eu iria te perder, não\nA tempestade vai se acalmar\nO rio sempre volta pro mar\nInevitavelmente um dia a gente vai voltar\nVai voltar, oh',

In [ ]:
tokenized_train = preprocess_function(req_train_dict)
tokenized_eval = preprocess_function(req_eval_dict)

In [35]:
training_args = TrainingArguments(
    output_dir="./Dataset",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
)

In [29]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_text,
    eval_dataset=tokenized_eval,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

ValueError: You have set `args.eval_strategy` to epoch but you didn't pass an `eval_dataset` to `Trainer`. Either set `args.eval_strategy` to `no` or pass an `eval_dataset`.